api_version = "3.0"

[[plugins]]
id = "add-to-collection"
uuid = "3713d8f5-72b0-401d-9ec9-3818380bc576"
name = "Add to Collection"
description = "Adds any saved release to one of your user collections"
git_url = "https://github.com/dvirtz/picard-plugin-add-to-collection"
categories = []
trust_level = "community"
authors = [
  "Dvir Yitzchaki (dvirtz@gmail.com)",
]
added_at = "2026-02-05T09:48:44Z"
updated_at = "2026-02-05T09:48:44Z"
versioning_scheme = "semver"

[[plugins]]
id = "additional-artists-details"
uuid = "81fd1f5f-f723-498f-a82e-17fb4163c83a"
name = "Additional Artists Details"
description = "This plugin provides specialized album and track variables with artist details for use in tagging and naming scripts."
git_url = "https://github.com/rdswift/picard-plugin-additional-artists-details"
categories = [
  "metadata",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
]
added_at = "2025-12-01T11:16:37Z"
updated_at = "2025-12-02T21:36:08Z"
versioning_scheme = "semver"

[plugins.name_i18n]
de = "Weitere Details zu den Künstlern"
fr = "Détails supplémentaires sur les artistes"

[plugins.description_i18n]
de = "Dieses Plugin stellt spezielle Album- und Titelvariablen mit Künstlerinformationen zur Verwendung in Tagging- und Benennungsskripten bereit."
fr = "Ce plugin fournit des variables spécialisées pour les albums et les pistes, avec des informations sur les artistes, à utiliser dans les scripts de balisage et de nommage."

[[plugins]]
id = "additional-artists-variables"
uuid = "2eae631a-1696-4bdc-841f-f75aaa3ae294"
name = "Additional Artists Variables"
description = "This plugin provides specialized album and track variables for use in naming scripts."
git_url = "https://github.com/rdswift/picard-plugin-additional-artists-variables"
categories = [
  "metadata",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
]
added_at = "2025-12-01T17:55:54Z"
updated_at = "2025-12-02T22:05:40Z"
versioning_scheme = "semver"

[plugins.name_i18n]
de = "Zusätzliche Künstlervariablen"
fr = "Variables supplémentaires relatives aux artistes"

[plugins.description_i18n]
de = "Dieses Plugin stellt spezielle Album- und Titelvariablen für die Verwendung in Benennungsskripten bereit."
fr = "Ce plugin fournit des variables spécialisées pour les albums et les pistes à utiliser dans les scripts de nommage."

[[plugins]]
id = "combine-performer-tags"
uuid = "4779bcaf-1bda-4580-8c55-1fbe28771ce8"
name = "Combine Performer Tags"
description = "This plugin combines all performer tags into a multi-value variable `%_performers%`."
git_url = "https://github.com/rdswift/picard-plugin-combine-performer-tags"
categories = [
  "metadata",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
]
added_at = "2025-12-03T18:05:22Z"
updated_at = "2025-12-03T18:07:53Z"
versioning_scheme = "semver"

[plugins.name_i18n]
de = "Performer-Tags kombinieren"
fr = "Combiner les balises Performer"

[plugins.description_i18n]
de = "Dieses Plugin fasst alle Performer-Tags in einer Mehrwertvariablen `%_performers%` zusammen."
fr = "Ce plugin combine toutes les balises performer dans une variable à valeurs multiples `%_performers%`."

[[plugins]]
id = "decade"
uuid = "1e6f5357-bbfb-4575-82fe-40706708af76"
name = "Decade function"
description = "Add a $decade(date) scripting function to get the decade from a year"
git_url = "https://git.sr.ht/~phw/picard-plugin-decade"
categories = [
  "scripting",
]
trust_level = "trusted"
authors = [
  "Philipp Wolfer",
]
added_at = "2025-12-20T16:31:47Z"
updated_at = "2026-04-27T18:03:12Z"
versioning_scheme = "semver"
homepage = "https://git.sr.ht/~phw/picard-plugin-decade"
license = "GPL-2.0-or-later"
license_url = "https://www.gnu.org/licenses/gpl-2.0.html"
long_description = """
Add a $decade(date) scripting function to get the decade from a year.

E.g. `$decade(1994-04-05)` will return \"90s\". By default decades between 1920 and 2000
will be shortened to two digits. You can disable this with setting the second parameter
to 0, e.g. `$decade(1994,0)` will return \"1990s\"."""
report_bugs_to = "https://todo.sr.ht/~phw/picard-plugins"

[[plugins]]
id = "fanarttv"
uuid = "d80f6f27-b141-438a-b644-fffb752e0ba2"
name = "fanart.tv cover art"
description = "Use cover art from fanart.tv"
git_url = "https://git.sr.ht/~phw/picard-plugin-fanarttv"
categories = [
  "coverart",
]
trust_level = "trusted"
authors = [
  "Philipp Wolfer",
  "Sambhav Kothari",
]
added_at = "2025-12-16T15:21:14Z"
updated_at = "2026-04-27T18:04:54Z"
versioning_scheme = "semver"
maintainers = [
  "Philipp Wolfer",
]
homepage = "https://git.sr.ht/~phw/picard-plugin-fanarttv"
license = "GPL-2.0-or-later"
license_url = "https://www.gnu.org/licenses/gpl-2.0.html"
long_description = """
Use cover art from fanart.tv.

To use this plugin you have to register a personal API key on [fanart.tv](https://fanart.tv/get-an-api-key/)."""
report_bugs_to = "https://todo.sr.ht/~phw/picard-plugins"

[[plugins]]
id = "format-performer-tags"
uuid = "2eb74c03-a488-4ffc-814d-20661782de95"
name = "Format Performer Tags"
description = "This plugin provides options with respect to the formatting of performer tags."
git_url = "https://github.com/rdswift/picard-plugin-format-performer-tags"
categories = [
  "metadata",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
  "Philipp Wolfer",
]
added_at = "2025-12-17T22:36:05Z"
updated_at = "2025-12-17T22:40:09Z"
versioning_scheme = "semver"

[[plugins]]
id = "genre-mapper"
uuid = "e8effffd-e057-467f-950c-f39d285920be"
name = "Genre Mapper"
description = """
This plugin provides the ability to standardize genres in the \"genre\"
tag by matching the genres as found to a standard genre as defined in
the genre replacement mapping configuration option."""
git_url = "https://github.com/rdswift/picard-plugin-genre-mapper"
categories = [
  "metadata",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
]
added_at = "2025-12-18T05:28:10Z"
updated_at = "2025-12-18T05:39:02Z"
versioning_scheme = "semver"

[[plugins]]
id = "haikuattrs"
uuid = "266d3e71-7d42-4ceb-bc88-8b4fd6720a45"
name = "Haiku BFS Attributes"
description = "Save and load metadata to/from Haiku BFS attributes."
git_url = "https://git.sr.ht/~phw/picard-plugin-haikuattrs"
categories = [
  "metadata",
]
trust_level = "trusted"
authors = [
  "Philipp Wolfer",
]
added_at = "2026-02-08T14:10:09Z"
updated_at = "2026-02-08T14:10:09Z"
versioning_scheme = "semver"

[[plugins]]
id = "keep-only-tags"
uuid = "910bba9b-6259-43ac-9ceb-c8d2b6908c18"
name = "Keep Only Tags"
description = "This plugin provides a different approach for the user to determine which tags are written to the output files by Picard."
git_url = "https://github.com/rdswift/picard-plugin-keep-only-tags"
categories = [
  "metadata",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
]
added_at = "2026-01-03T00:35:27Z"
updated_at = "2026-01-03T00:35:27Z"
versioning_scheme = "semver"

[[plugins]]
id = "key-wheel-converter"
uuid = "acc16641-5c1d-4589-9909-e411f816e3fb"
name = "Key Wheel Converter"
description = """
Adds functions to convert between 'standard', 'camelot', 'open key' and 'traktor' key formats.
"""
git_url = "https://github.com/rdswift/picard-plugin-key-wheel-converter"
categories = [
  "scripting",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
]
added_at = "2025-12-20T03:35:29Z"
updated_at = "2025-12-20T03:41:24Z"
versioning_scheme = "semver"

[[plugins]]
id = "label-variables"
uuid = "d63dfdbf-b2cc-446c-9f42-fb0e69213e6b"
name = "Label Variables"
description = "This plugin provides variables containing label information for a release for use in user or file naming scripts."
git_url = "https://github.com/rdswift/picard-plugin-label-variables"
categories = [
  "metadata",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
]
added_at = "2025-12-27T01:44:31Z"
updated_at = "2025-12-27T01:44:31Z"
versioning_scheme = "semver"

[[plugins]]
id = "language-name"
uuid = "90505bdf-6676-4d54-98af-89e965606123"
name = "Language Name"
description = "This plugin provides a new script function `$language_name()` to replace the three-character language code with the full name of the language."
git_url = "https://github.com/rdswift/picard-plugin-language-name"
categories = [
  "scripting",
  "metadata",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
]
added_at = "2025-12-31T21:51:46Z"
updated_at = "2025-12-31T21:51:46Z"
versioning_scheme = "semver"

[[plugins]]
id = "loadasnat"
uuid = "263cb3c3-2c44-4f31-9bc9-72010ffc1725"
name = "Load as standalone recording"
description = "Allows loading selected tracks as standalone recordings."
git_url = "https://git.sr.ht/~phw/picard-plugin-loadasnat"
categories = [
  "ui",
  "metadata",
]
trust_level = "trusted"
authors = [
  "Philipp Wolfer",
]
added_at = "2025-12-18T16:56:18Z"
updated_at = "2025-12-18T16:56:18Z"
versioning_scheme = "semver"

[[plugins]]
id = "losslessfuncs"
uuid = "2bc76f6c-464f-4565-b1ac-1dbaab6113ab"
name = "Tagger script functions $is_lossless() and $is_lossy()"
description = "Tagger script functions to detect if a file is lossless or lossy"
git_url = "https://git.sr.ht/~phw/picard-plugin-losslessfuncs"
categories = [
  "scripting",
]
trust_level = "trusted"
authors = [
  "Philipp Wolfer",
]
added_at = "2025-12-20T14:24:01Z"
updated_at = "2025-12-20T14:24:01Z"
versioning_scheme = "semver"

[[plugins]]
id = "mod"
uuid = "2e8596ef-0ee2-444b-b69b-92463c09f22b"
name = "MOD files"
description = "Support for loading and renaming various tracker module formats"
git_url = "https://git.sr.ht/~phw/picard-plugin-mod"
categories = [
  "formats",
]
trust_level = "trusted"
authors = [
  "Philipp Wolfer",
]
added_at = "2025-12-17T18:42:57Z"
updated_at = "2025-12-17T18:42:57Z"
versioning_scheme = "semver"

[[plugins]]
id = "opencc"
uuid = "9493e89d-ca13-4be3-9ed6-a2d6195dfce9"
name = "Chinese script conversion"
description = "Convert track listings between Traditional Chinese and Simplified Chinese script."
git_url = "https://git.sr.ht/~phw/picard-plugin-opencc"
categories = [
  "scripting",
  "ui",
]
trust_level = "trusted"
authors = [
  "Philipp Wolfer",
]
added_at = "2026-04-22T08:09:52Z"
updated_at = "2026-04-22T08:09:52Z"
license = "MIT"
license_url = "https://opensource.org/licenses/MIT"
long_description = """
Convert track listings between Traditional Chinese and Simplified Chinese script.

The conversion can be done manually or with scripting. For manual use right click
on album, tracks, clusters or files and choose the \"Convert to Simplified Chinese\"
or \"Convert to Simplified Chinese\" action.

For scripting you can use the following tagger functions:

- `$convert_to_simplified_chinese(text)`
- `$convert_to_traditional_chinese(text)`"""
versioning_scheme = "semver"

[[plugins]]
id = "performer-tag-replace"
uuid = "e561da4b-5b0c-4bc0-a8f6-d5384e445669"
name = "Performer Tag Replace"
description = """
This plugin provides the ability to replace text in performer tags.
"""
git_url = "https://github.com/rdswift/picard-plugin-performer-tag-replace"
categories = [
  "metadata",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
]
added_at = "2025-12-20T19:18:28Z"
updated_at = "2025-12-20T19:19:06Z"
versioning_scheme = "semver"

[[plugins]]
id = "persistent-variables"
uuid = "aa0f0588-84e0-4f5b-aa32-17657b4434a1"
name = "Persistent Variables"
description = "This plugin provides the ability to store and retrieve script variables that persist across tracks and albums."
git_url = "https://github.com/rdswift/picard-plugin-persistent-variables"
categories = [
  "metadata",
  "scripting",
  "ui",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
]
added_at = "2025-12-04T04:10:55Z"
updated_at = "2025-12-04T04:10:55Z"
versioning_scheme = "semver"

[plugins.name_i18n]
de = "Persistente Variablen"
fr = "Variables persistantes"

[plugins.description_i18n]
de = "Dieses Plugin bietet die Möglichkeit, Skriptvariablen zu speichern und abzurufen, die über Titel und Alben hinweg bestehen bleiben."
fr = "Ce plugin permet de stocker et de récupérer des variables de script qui persistent d'une piste à l'autre et d'un album à l'autre."

[[plugins]]
id = "replaygain2"
uuid = "74807b76-c451-419f-bbd4-42a78e2444a6"
name = "ReplayGain 2.0"
description = "Calculates ReplayGain information for tracks and albums"
git_url = "https://github.com/metabrainz/picard-plugin-replaygain2.git"
categories = [
  "metadata",
  "ui",
]
trust_level = "official"
authors = [
  "complexlogic",
  "Philipp Wolfer",
]
added_at = "2025-12-20T15:25:15Z"
updated_at = "2025-12-20T15:25:15Z"
maintainers = [
  "MusicBrainz Picard Team",
]
versioning_scheme = "semver"

[[plugins]]
id = "script-logger"
uuid = "c32678a7-094b-4f9b-86f8-ff3a786cc9e4"
name = "Script Logger"
description = "This plugin provides a new script function `$logline()` to write entries to Picard's system log."
git_url = "https://github.com/rdswift/picard-plugin-script-logger"
categories = [
  "scripting",
  "other",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
]
added_at = "2025-12-20T21:21:58Z"
updated_at = "2025-12-20T21:22:24Z"
versioning_scheme = "semver"

[[plugins]]
id = "search-engine-lookup"
uuid = "f1b9e97e-8077-4104-86a7-836a04ad9eac"
name = "Search Engine Lookup"
description = "Adds a right-click option on a cluster to look up album information using a search engine in a browser window."
git_url = "https://github.com/rdswift/picard-plugin-search-engine-lookup"
categories = [
  "other",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
]
added_at = "2025-12-23T00:22:33Z"
updated_at = "2025-12-23T00:22:33Z"
versioning_scheme = "semver"

[[plugins]]
id = "submit-isrc"
uuid = "bbaa987c-8ebf-412f-af6f-70c79e63bb51"
name = "Submit ISRC"
description = "Adds a right click option on an album to submit the ISRCs to the MusicBrainz server specified in the Options."
git_url = "https://github.com/rdswift/picard-plugin-submit-isrc"
categories = [
  "metadata",
  "other",
]
trust_level = "trusted"
authors = [
  "Bob Swift",
]
added_at = "2025-12-22T21:11:44Z"
updated_at = "2025-12-22T21:11:44Z"
versioning_scheme = "semver"

[[plugins]]
id = "theaudiodb"
uuid = "ed113c88-25af-4e35-b046-993226cdd46a"
name = "TheAudioDB cover art"
description = "Use cover art from TheAudioDB"
git_url = "https://git.sr.ht/~phw/picard-plugin-theaudiodb"
categories = [
  "coverart",
]
trust_level = "trusted"
authors = [
  "Philipp Wolfer",
]
added_at = "2025-12-21T00:06:02Z"
updated_at = "2025-12-21T00:06:02Z"
versioning_scheme = "semver"

[[plugins]]
id = "view-script-variables"
uuid = "62e2a3fd-f4df-4b53-abc5-b73d2a36b672"
name = "View script variables"
description = "Display a dialog box listing the metadata tags and variables for the track / file."
git_url = "https://github.com/metabrainz/picard-plugin-view-script-variables"
categories = [
  "metadata",
  "ui",
]
trust_level = "official"
authors = [
  "Sophist",
]
added_at = "2025-12-03T23:44:25Z"
updated_at = "2025-12-22T18:12:02Z"
maintainers = [
  "MusicBrainz Picard Team",
]
versioning_scheme = "semver"
redirect_from = [
  "https://github.com/rdswift/picard-plugin-view-script-variables",
]

[plugins.name_i18n]
de = "Script-Variablen anzeigen"
fr = "Afficher les variables du script"

[plugins.description_i18n]
de = "Zeigen Sie ein Dialogfeld an, in dem die Metadaten-Tags und Variablen für den Titel/die Datei aufgelistet sind."
fr = "Affichez une boîte de dialogue répertoriant les balises de métadonnées et les variables pour la piste/le fichier."

[[plugins]]
id = "workandmovement"
uuid = "c8d51698-cbd9-45d7-9c61-2e9824992337"
name = "Work & Movement"
description = "Set work and movement based on work relationships."
git_url = "https://git.sr.ht/~phw/picard-plugin-workandmovement"
categories = [
  "metadata",
]
trust_level = "trusted"
authors = [
  "Philipp Wolfer",
]
added_at = "2025-12-17T16:26:15Z"
updated_at = "2025-12-17T16:26:15Z"
versioning_scheme = "semver"

[plugins.name_i18n]
de = "Werk & Satz"

[plugins.description_i18n]
de = "Werk und Satz anhand von Werkbeziehungen setzen."

[[plugins]]
id = "xqaf"
uuid = "88a16689-663b-4d78-bc1c-2fd7698e51b0"
name = "XQAF"
description = "Support for the XQAF and QOA audio files"
git_url = "https://git.sr.ht/~phw/picard-plugin-xqaf"
categories = [
  "formats",
]
trust_level = "trusted"
authors = [
  "Philipp Wolfer",
]
added_at = "2025-12-05T20:01:04Z"
updated_at = "2026-04-27T18:01:18Z"
versioning_scheme = "semver"
homepage = "https://git.sr.ht/~phw/picard-plugin-xqaf"
license = "GPL-3.0-or-later"
license_url = "https://www.gnu.org/licenses/gpl-3.0.html"
long_description = """
This plugin allows Picard to read and write XQAF and QOA audio file formats.

XQAF files support full tagging. QOA files do not store tags, but can be
loaded and renamed.

For more details about both formats see
[Introducing the Extended QOA Format for Audio](https://remilia.sdf.org/blog/2025-06-14-a.html)
and [The Quite OK Audio Format](https://qoaformat.org/)."""
report_bugs_to = "https://todo.sr.ht/~phw/picard-plugins"

[plugins.description_i18n]
de = "Unterstützung für XQAF- und QOA-Audiodateien"

[plugins.long_description_i18n]
de = """
Dieses Plugin ermöglicht es Picard, die Audio-Dateiformate XQAF und QOA zu lesen und zu schreiben.

XQAF-Dateien unterstützen vollständiges Tagging. QOA-Dateien speichern keine Tags,
können aber geladen und umbenannt werden.

Weitere Details zu beiden Formaten finden sich unter
[Introducing the Extended QOA Format for Audio](https://remilia.sdf.org/blog/2025-06-14-a.html)
und [The Quite OK Audio Format](https://qoaformat.org/)."""
